### ISSUE TITLE
cannot successfully run Jupyter notebook

### ISSUE THREAD

**Issue by JackDougherty** [OnTheLine/otl-oldschoolct#1]
@ilyankou  -- I tried to run the Jupyter notebook to capture new Instragram images and data that the photographer has recently uploaded, but did not succeed. 
- I opened the notebook with Anaconda
- Tried to "run" and also "restart the kernel and run" but "Module not found" errors (see screenshot)

If I can run this, I will manually transfer new data from catalog.csv to catalog-refined.csv

<img width="1180" alt="Screen Shot 2020-03-16 at 11 06 49 AM" src="https://user-images.githubusercontent.com/649719/76772055-a4fbf900-6776-11ea-99cc-4afe89414b86.png">

**Comment by ilyankou** [comment]
In your Terminal, try running `pip install instaloader` and then run the notebook again. Do this for all other missing modules.

**Comment by JackDougherty** [comment]
thanks
