### ISSUE TITLE
fewer thumbnail images are displayed on map

### ISSUE THREAD

**Issue by JackDougherty** [OnTheLine/otl-oldschoolct#3]
@ilyankou  --  Did I screw up something when making edits to the catalog-refined.csv, or some other part of the code?

Fewer thumbnail images are displayed on the map now versus earlier today. See evidence in the screenshot below, which shows the new demo.png I took earlier today, versus the live map now. Several schools are missing. One specific example is row 177, Northwest school in Hartford, which previously was visible on the live map, but no longer appears, even when zooming into Hartford Albany Ave area.

I explored the catalog-refined.csv file. It's messy because the photographer had some very long titles and captions, but I see no pattern in what appears and what is missing.

Earlier today I moved a column named "TempJupyter..." from catalog-refined.csv, which held your processed LatLng data from the instagram captions. I removed it because I am *pretty sure* that the code pulls locations directly from the Latitude and Longitude columns. Tell me if I'm wrong about that.

![Screen Shot 2020-03-17 at 2 27 53 PM](https://user-images.githubusercontent.com/649719/76889521-1a8dc500-685c-11ea-88aa-35888f35bd26.png)

**Comment by ilyankou** [comment]
Jack, there was an error rendering one of the longitudes (`?` at the beginning in `catalog-refine.csv`, so not a valid numeric), which prevented the script from generating all further markers:

![Screenshot 2020-03-18 at 07 45 49](https://user-images.githubusercontent.com/10443203/76937819-6b99c980-68ed-11ea-921d-67f531fdb737.png)

I removed the question mark symbol and it now works fine. I also added try/catch blocks to where it generates markers, so if it happens in the future, you will see a nice warning for each invalid marker in the console, and the map will continue adding valid markers ([see commit](https://github.com/OnTheLine/otl-oldschoolct/commit/c950844e8c0e92e013fecaf9305b4efe5b4b20b2#diff-eacf331f0ffc35d4b482f1d15a887d3bL140))

![Screenshot 2020-03-18 at 07 50 44](https://user-images.githubusercontent.com/10443203/76937965-b4518280-68ed-11ea-9867-5aeb2cf47785.png)

I also fixed the URL in readme, and added an active link to my GitHub account.
